In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Datasets/veriler.csv")

In [3]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
cinsiyet = data.iloc[:,-1].values
cinsiyet = le.fit_transform(cinsiyet).reshape(-1, 1)

In [4]:
ohe = preprocessing.OneHotEncoder()
cinsiyet = ohe.fit_transform(cinsiyet).toarray()

In [5]:
cinsiyet

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [6]:
cinsiyet = pd.DataFrame(data=cinsiyet[:,0],columns=["cinsiyet"],index=range(len(cinsiyet)))

In [7]:
cinsiyet

cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0

In [8]:
ulke = data.iloc[:,0].values
yas = data.iloc[:,1:4].values
ulke = le.fit_transform(ulke).reshape(-1, 1)
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
sonuc = pd.DataFrame(data=ulke,columns=["fr","tr","us"])
yas =pd.DataFrame(data=yas,index=range(22),columns=["boy","kilo","yas"])
s = pd.concat([sonuc,yas],axis=1)

In [9]:
dataFrame2 = pd.concat([s,cinsiyet],axis=1)

In [10]:
dataFrame2

fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   42       0.0

In [11]:
from sklearn.model_selection import train_test_split
y = dataFrame2["cinsiyet"].values
x = dataFrame2.drop("cinsiyet", axis = 1).values
xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.33)

In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(xTrain,yTrain)
tahmin = lr.predict(xTest)

In [13]:
tahmin

array([ 1.30289801, -0.15916514,  1.25920523,  0.43030587,  0.36492484,
        0.8857354 ,  0.38759757,  0.93052392])

In [14]:
yTest

array([1., 0., 1., 1., 0., 1., 1., 0.])

In [15]:
boy = dataFrame2.iloc[:,3]
boy

0     130
1     125
2     135
3     133
4     129
5     180
6     190
7     175
8     177
9     185
10    165
11    155
12    160
13    162
14    167
15    174
16    193
17    187
18    183
19    159
20    164
21    166
Name: boy, dtype: int64

In [16]:
veri = dataFrame2.drop(["boy"],axis=1)

In [17]:
veri

fr   tr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0

In [18]:
xTrain,xTest,yTrain,yTest = train_test_split(veri,boy,test_size=0.33)

In [19]:
lr2 = LinearRegression()
lr2.fit(xTrain,yTrain)
tahmin2 = lr2.predict(xTest)
tahmin2

array([150.01735474, 142.1038322 , 184.68608736, 134.73008535,
       185.52709161, 162.30179884, 189.37703808, 160.97733903])

In [20]:
yTest


19    159
2     135
18    183
1     125
16    193
13    162
7     175
12    160
Name: boy, dtype: int64

In [21]:
import statsmodels.api as sm

x = np.append(arr = np.ones((22,1)).astype(int), values=veri.to_numpy(), axis=1)

In [22]:
x

array([[  1.,   0.,   1.,   0.,  30.,  10.,   1.],
       [  1.,   0.,   1.,   0.,  36.,  11.,   1.],
       [  1.,   0.,   1.,   0.,  34.,  10.,   0.],
       [  1.,   0.,   1.,   0.,  30.,   9.,   0.],
       [  1.,   0.,   1.,   0.,  38.,  12.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  30.,   1.],
       [  1.,   0.,   1.,   0.,  80.,  25.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  35.,   1.],
       [  1.,   0.,   1.,   0.,  60.,  22.,   0.],
       [  1.,   0.,   0.,   1., 105.,  33.,   1.],
       [  1.,   0.,   0.,   1.,  55.,  27.,   0.],
       [  1.,   0.,   0.,   1.,  50.,  44.,   0.],
       [  1.,   0.,   0.,   1.,  58.,  39.,   0.],
       [  1.,   0.,   0.,   1.,  59.,  41.,   0.],
       [  1.,   0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   1.,   0.,   0.,

In [23]:
xList = veri.iloc[:,[0,1,2,3,4,5]]

In [24]:
xList= np.array(xList,dtype=float)

In [25]:
model = sm.OLS(boy,xList).fit()

In [26]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Mon, 08 Jul 2024   Prob (F-statistic):           5.41e-07
Time:                        08:07:22   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.000      96.802     131.335
x2           108.3030      5.736     18.880      0.000      96.143     120.463
x3           104.4714      9.195     11.361      0.000      84.978     123.964
x4             0.9211      0.119      7.737      0.000       0.669       1.174
x5             0.0814      0.221      0.369      0.717      -0.386       0.549
x6           -10.5980      5.052     -2.098      0.052     -21.308       0.112
==============================================================================
Omnibus:                        1.031   Durbin-Watson:                   2.759
Prob(Omnibus):                  0.597   Jarque-Bera (JB):                0.624
Skew:                           0.407   Prob(JB):                        0.732
Kurtosis:                       2.863   Cond. No.                         524.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [27]:
xList = veri.iloc[:,[0,1,2,3,5]]
xList= np.array(xList,dtype=float)
model = sm.OLS(boy,xList).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Mon, 08 Jul 2024   Prob (F-statistic):           9.32e-08
Time:                        08:07:22   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.000     101.451     129.866
x2           109.0786      5.200     20.978      0.000      98.108     120.049
x3           106.5445      7.090     15.026      0.000      91.585     121.504
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5           -11.1093      4.733     -2.347      0.031     -21.096      -1.123
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         397.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
xList = veri.iloc[:,[0,1,2,3]]
xList= np.array(xList,dtype=float)
model = sm.OLS(boy,xList).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Mon, 08 Jul 2024   Prob (F-statistic):           1.52e-07
Time:                        08:07:22   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.000     104.550     135.077
x2           109.8084      5.804     18.919      0.000      97.615     122.002
x3           114.4212      6.984     16.382      0.000      99.747     129.095
x4             0.7904      0.092      8.595      0.000       0.597       0.984
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.855
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                1.499
Skew:                           0.605   Prob(JB):                        0.473
Kurtosis:                       3.416   Cond. No.                         369.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [77]:
from sklearn.metrics import r2_score
y = dataFrame2["boy"].values
x = dataFrame2.iloc[:,[0,1,2,4]].values
xTrain,xTest,yTrain,yTest = train_test_split(x,y,test_size=0.33)
lr.fit(xTrain,yTrain)
tahmin = lr.predict(xTrain)
print("Multiple Linear Regression R2 değerleri:")
r2_score(yTrain,tahmin)

Multiple Linear Regression R2 değerleri:


0.8645485327725568