In [94]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [34]:
Review = []
Liked = []
with open("Datasets/Restaurant_Reviews.csv", "r", encoding='utf-8') as file:
    for line in file:
        parts = line.rsplit('.', 1)
        if len(parts) == 2:
            review = parts[0].strip()  # Yorumu temizle
            sentiment = parts[1].strip()  # Kategoriyi temizle
            Review.append(review)
            Liked.append(sentiment)
Liked = [int(''.join([char for char in s if char.isdigit()])) for s in Liked]# DataFrame oluştur
data = pd.DataFrame({'Review': Review, 'Liked': Liked})

In [55]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Furkan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [54]:
ps = PorterStemmer()

In [59]:
#preprocessig
comments = []
for i in range(len(data)):    
    comment = re.sub("[^a-zA-Z]"," ",data["Review"][i])
    comment = comment.lower()
    comment = comment.split()
    comment = [ps.stem(word) for word in comment if not word in set(stopwords.words("english"))]
    comment = " ".join(comment)
    comments.append(comment)

In [79]:
#Feature Extraction
#BOW --> Bag of Words
cv = CountVectorizer(max_features=2000)
x= cv.fit_transform(comments).toarray()
y = data["Liked"].values


In [83]:
xTrain,xtest,yTrain,yTest = train_test_split(x,y,test_size=0.20)

In [96]:
gnb = GaussianNB()
gnb.fit(xTrain,yTrain)
tahmin = gnb.predict(xtest)
print(confusion_matrix(yTest,tahmin))
accuracy_score(yTest,tahmin)

[[46 39]
 [18 64]]


0.6586826347305389

In [95]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(xTrain,yTrain)
y_pred = logr.predict(xtest)
print(confusion_matrix(yTest,y_pred))
accuracy_score(yTest,y_pred)

[[69 16]
 [21 61]]


0.7784431137724551

In [97]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7, metric='nan_euclidean')
knn.fit(xTrain,yTrain)
y_pred = knn.predict(xtest)
print(confusion_matrix(yTest,y_pred))
accuracy_score(yTest,y_pred)

[[77  8]
 [48 34]]


0.6646706586826348

In [98]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf')
svc.fit(xTrain,yTrain)
y_pred = svc.predict(xtest)
print(confusion_matrix(yTest,y_pred))
accuracy_score(yTest,y_pred)

[[78  7]
 [36 46]]


0.7425149700598802

In [99]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy')
dtc.fit(xTrain,yTrain)
y_pred = dtc.predict(xtest)
print(confusion_matrix(yTest,y_pred))
accuracy_score(yTest,y_pred)

[[75 10]
 [29 53]]


0.7664670658682635

In [100]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion = 'gini')
rfc.fit(xTrain,yTrain)
y_pred = rfc.predict(xtest)
print(confusion_matrix(yTest,y_pred))
accuracy_score(yTest,y_pred)

[[78  7]
 [36 46]]


0.7425149700598802