In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [2]:
veriler = pd.read_csv('Datasets/veriler.csv')

x = veriler.iloc[:,1:4]
y = veriler.iloc[:,4]
X = x.values
Y = y.values

In [3]:
xTrain, xTest, yTrain, yTest = train_test_split(x,y,test_size=0.33,random_state=0)

In [4]:
sc = StandardScaler()
sc.fit_transform(xTrain)
sc.transform(xTest)

array([[-0.10726058, -0.05470872,  0.6225517 ],
       [-0.06435635, -0.49813728,  0.17787191],
       [ 0.02145212, -0.21595547,  2.66807872],
       [-0.19306904, -0.33689053,  1.42297532],
       [-1.78052563, -1.26405934, -1.2451034 ],
       [-0.02145212, -0.45782559,  1.51191128],
       [-0.49339867, -0.69969571,  1.68978319],
       [-0.32178174, -1.10281259,  0.35574383]])

In [5]:
logr = LogisticRegression(random_state=0)
logr.fit(xTrain,yTrain)
tahmin = logr.predict(xTest)

In [6]:
print(tahmin, "\n\n", yTest)

['e' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

 20    k
10    k
14    k
13    k
1     e
21    k
11    k
19    k
Name: cinsiyet, dtype: object


In [7]:
cm = confusion_matrix(yTest,tahmin)
cm

array([[1, 0],
       [1, 6]], dtype=int64)

In [8]:
knn = KNeighborsClassifier(n_neighbors=1,metric="minkowski")
knn.fit(xTrain,yTrain)

tahmin2 = knn.predict(xTest)

In [9]:
confusion_matrix(yTest,tahmin2)

array([[1, 0],
       [1, 6]], dtype=int64)